services:

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - pg

  pg:
    image: postgres
    environment:
      POSTGRES_DB: Dimatech
      POSTGRES_USER: Dimatech
      POSTGRES_PASSWORD: Dimatech
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
